// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: conduit.proto

// Package conduit defines the high-performance, service-to-service gRPC surface
// for TPT Conduit. It mirrors the core engine mutations and read APIs so that
// other services (workers, integrations, the Next.js frontend via a gateway)
// can drive the durable workflow engine without going through GraphQL.

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Ticket is the generic, domain-agnostic unit of work. All structured data
// lives in fields_json (a JSON document) so one engine serves every domain.
type Ticket struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Workflow        string                 `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	WorkflowVersion string                 `protobuf:"bytes,3,opt,name=workflow_version,json=workflowVersion,proto3" json:"workflow_version,omitempty"`
	Title           string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	FieldsJson      string                 `protobuf:"bytes,5,opt,name=fields_json,json=fieldsJson,proto3" json:"fields_json,omitempty"`
	Assignee        string                 `protobuf:"bytes,6,opt,name=assignee,proto3" json:"assignee,omitempty"`
	Queue           string                 `protobuf:"bytes,7,opt,name=queue,proto3" json:"queue,omitempty"`
	Priority        string                 `protobuf:"bytes,8,opt,name=priority,proto3" json:"priority,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Ticket) Reset() {
	*x = Ticket{}
	mi := &file_conduit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ticket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticket) ProtoMessage() {}

func (x *Ticket) ProtoReflect() protoreflect.Message {
	mi := &file_conduit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ticket.ProtoReflect.Descriptor instead.
func (*Ticket) Descriptor() ([]byte, []int) {
	return file_conduit_proto_rawDescGZIP(), []int{0}
}

func (x *Ticket) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Ticket) GetWorkflow() string {
	if x != nil {
		return x.Workflow
	}
	return ""
}

func (x *Ticket) GetWorkflowVersion() string {
	if x != nil {
		return x.WorkflowVersion
	}
	return ""
}

func (x *Ticket) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Ticket) GetFieldsJson() string {
	if x != nil {
		return x.FieldsJson
	}
	return ""
}

func (x *Ticket) GetAssignee() string {
	if x != nil {
		return x.Assignee
	}
	return ""
}

func (x *Ticket) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *Ticket) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *Ticket) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Ticket) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// WorkflowDef is the shared internal workflow definition (IR). The detailed
// step graph is consumed via GraphQL; gRPC carries identity + metadata for
// service-to-service discovery and registration confirmation.
type WorkflowDef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Initial       string                 `protobuf:"bytes,4,opt,name=initial,proto3" json:"initial,omitempty"`
	StepCount     int32                  `protobuf:"varint,5,opt,name=step_count,json=stepCount,proto3" json:"step_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowDef) Reset() {
	*x = WorkflowDef{}
	mi := &file_conduit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowDef) ProtoMessage() {}

func (x *WorkflowDef) ProtoReflect() protoreflect.Message {
	mi := &file_conduit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowDef.ProtoReflect.Descriptor instead.
func (*WorkflowDef) Descriptor() ([]byte, []int) {
	return file_conduit_proto_rawDescGZIP(), []int{1}
}

func (x *WorkflowDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkflowDef) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *WorkflowDef) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WorkflowDef) GetInitial() string {
	if x != nil {
		return x.Initial
	}
	return ""
}

func (x *WorkflowDef) GetStepCount() int32 {
	if x != nil {
		return x.StepCount
	}
	return 0
}

// WorkflowRun is the derived (replayed) state of a workflow execution.
type WorkflowRun struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TicketId        string                 `protobuf:"bytes,2,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	Workflow        string                 `protobuf:"bytes,3,opt,name=workflow,proto3" json:"workflow,omitempty"`
	WorkflowVersion string                 `protobuf:"bytes,4,opt,name=workflow_version,json=workflowVersion,proto3" json:"workflow_version,omitempty"`
	Status          string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CurrentStep     string                 `protobuf:"bytes,6,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	OutputJson      string                 `protobuf:"bytes,7,opt,name=output_json,json=outputJson,proto3" json:"output_json,omitempty"`
	Failed          bool                   `protobuf:"varint,8,opt,name=failed,proto3" json:"failed,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WorkflowRun) Reset() {
	*x = WorkflowRun{}
	mi := &file_conduit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowRun) ProtoMessage() {}

func (x *WorkflowRun) ProtoReflect() protoreflect.Message {
	mi := &file_conduit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowRun.ProtoReflect.Descriptor instead.
func (*WorkflowRun) Descriptor() ([]byte, []int) {
	return file_conduit_proto_rawDescGZIP(), []int{2}
}

func (x *WorkflowRun) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkflowRun) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *WorkflowRun) GetWorkflow() string {
	if x != nil {
		return x.Workflow
	}
	return ""
}

func (x *WorkflowRun) GetWorkflowVersion() string {
	if x != nil {
		return x.WorkflowVersion
	}
	return ""
}

func (x *WorkflowRun) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkflowRun) GetCurrentStep() string {
	if x != nil {
		return x.CurrentStep
	}
	return ""
}

func (x *WorkflowRun) GetOutputJson() string {
	if x != nil {
		return x.OutputJson
	}
	return ""
}

func (x *WorkflowRun) GetFailed() bool {
	if x != nil {
		return x.Failed
	}
	return false
}

type CreateTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workflow      string                 `protobuf:"bytes,1,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	FieldsJson    string                 `protobuf:"bytes,4,opt,name=fields_json,json=fieldsJson,proto3" json:"fields_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTicketRequest) Reset() {
	*x = CreateTicketRequest{}
	mi := &file_conduit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTicketRequest) ProtoMessage() {}

func (x *CreateTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conduit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTicketRequest.ProtoReflect.Descriptor instead.
func (*CreateTicketRequest) Descriptor() ([]byte, []int) {
	return file_conduit_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTicketRequest) GetWorkflow() string {
	if x != nil {
		return x.Workflow
	}
	return ""
}

func (x *CreateTicketRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CreateTicketRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTicketRequest) GetFieldsJson() string {
	if x != nil {
		return x.FieldsJson
	}
	return ""
}

type CreateTicketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticket        *Ticket                `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTicketResponse) Reset() {
	*x = CreateTicketResponse{}
	mi := &file_conduit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTicketResponse) ProtoMessage() {}

func (x *CreateTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conduit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTicketResponse.ProtoReflect.Descriptor instead.
func (*CreateTicketResponse) Descriptor() ([]byte, []int) {
	return file_conduit_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTicketResponse) GetTicket() *Ticket {
	if x != nil {
		return x.Ticket
	}
	return nil
}

type ApproveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Step          string                 `protobuf:"bytes,2,opt,name=step,proto3" json:"step,omitempty"`
	By            string                 `protobuf:"bytes,3,opt,name=by,proto3" json:"by,omitempty"`
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveRequest) Reset() {
	*x = ApproveRequest{}
	mi := &file_conduit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveRequest) ProtoMessage() {}

func (x *ApproveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conduit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveRequest.ProtoReflect.Descriptor instead.
func (*ApproveRequest) Descriptor() ([]byte, []int) {
	return file_conduit_proto_rawDescGZIP(), []int{5}
}

func (x *ApproveRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ApproveRequest) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *ApproveRequest) GetBy() string {
	if x != nil {
		return x.By
	}
	return ""
}

func (x *ApproveRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type RejectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Step          string                 `protobuf:"bytes,2,opt,name=step,proto3" json:"step,omitempty"`
	By            string                 `protobuf:"bytes,3,opt,name=by,proto3" json:"by,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectRequest) Reset() {
	*x = RejectRequest{}
	mi := &file_conduit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectRequest) ProtoMessage() {}

func (x *RejectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conduit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectRequest.ProtoReflect.Descriptor instead.
func (*RejectRequest) Descriptor() ([]byte, []int) {
	return file_conduit_proto_rawDescGZIP(), []int{6}
}

func (x *RejectRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RejectRequest) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *RejectRequest) GetBy() string {
	if x != nil {
		return x.By
	}
	return ""
}

func (x *RejectRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_conduit_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conduit_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_conduit_proto_rawDescGZIP(), []int{7}
}

func (x *CancelRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *CancelRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_conduit_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_conduit_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_conduit_proto_rawDescGZIP(), []int{8}
}

type GetTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTicketRequest) Reset() {
	*x = GetTicketRequest{}
	mi := &file_conduit_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketRequest) ProtoMessage() {}

func (x *GetTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conduit_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketRequest.ProtoReflect.Descriptor instead.
func (*GetTicketRequest) Descriptor() ([]byte, []int) {
	return file_conduit_proto_rawDescGZIP(), []int{9}
}

func (x *GetTicketRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListTicketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTicketsRequest) Reset() {
	*x = ListTicketsRequest{}
	mi := &file_conduit_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTicketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTicketsRequest) ProtoMessage() {}

func (x *ListTicketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conduit_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTicketsRequest.ProtoReflect.Descriptor instead.
func (*ListTicketsRequest) Descriptor() ([]byte, []int) {
	return file_conduit_proto_rawDescGZIP(), []int{10}
}

type ListTicketsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tickets       []*Ticket              `protobuf:"bytes,1,rep,name=tickets,proto3" json:"tickets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTicketsResponse) Reset() {
	*x = ListTicketsResponse{}
	mi := &file_conduit_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTicketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTicketsResponse) ProtoMessage() {}

func (x *ListTicketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conduit_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTicketsResponse.ProtoReflect.Descriptor instead.
func (*ListTicketsResponse) Descriptor() ([]byte, []int) {
	return file_conduit_proto_rawDescGZIP(), []int{11}
}

func (x *ListTicketsResponse) GetTickets() []*Ticket {
	if x != nil {
		return x.Tickets
	}
	return nil
}

type GetRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunRequest) Reset() {
	*x = GetRunRequest{}
	mi := &file_conduit_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunRequest) ProtoMessage() {}

func (x *GetRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conduit_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunRequest.ProtoReflect.Descriptor instead.
func (*GetRunRequest) Descriptor() ([]byte, []int) {
	return file_conduit_proto_rawDescGZIP(), []int{12}
}

func (x *GetRunRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Run           *WorkflowRun           `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunResponse) Reset() {
	*x = GetRunResponse{}
	mi := &file_conduit_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunResponse) ProtoMessage() {}

func (x *GetRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conduit_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunResponse.ProtoReflect.Descriptor instead.
func (*GetRunResponse) Descriptor() ([]byte, []int) {
	return file_conduit_proto_rawDescGZIP(), []int{13}
}

func (x *GetRunResponse) GetRun() *WorkflowRun {
	if x != nil {
		return x.Run
	}
	return nil
}

type ListRunsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunsRequest) Reset() {
	*x = ListRunsRequest{}
	mi := &file_conduit_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunsRequest) ProtoMessage() {}

func (x *ListRunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conduit_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunsRequest.ProtoReflect.Descriptor instead.
func (*ListRunsRequest) Descriptor() ([]byte, []int) {
	return file_conduit_proto_rawDescGZIP(), []int{14}
}

type ListRunsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runs          []*WorkflowRun         `protobuf:"bytes,1,rep,name=runs,proto3" json:"runs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunsResponse) Reset() {
	*x = ListRunsResponse{}
	mi := &file_conduit_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunsResponse) ProtoMessage() {}

func (x *ListRunsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conduit_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunsResponse.ProtoReflect.Descriptor instead.
func (*ListRunsResponse) Descriptor() ([]byte, []int) {
	return file_conduit_proto_rawDescGZIP(), []int{15}
}

func (x *ListRunsResponse) GetRuns() []*WorkflowRun {
	if x != nil {
		return x.Runs
	}
	return nil
}

type GetWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowRequest) Reset() {
	*x = GetWorkflowRequest{}
	mi := &file_conduit_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowRequest) ProtoMessage() {}

func (x *GetWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conduit_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowRequest.ProtoReflect.Descriptor instead.
func (*GetWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_conduit_proto_rawDescGZIP(), []int{16}
}

func (x *GetWorkflowRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetWorkflowRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type WorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workflow      *WorkflowDef           `protobuf:"bytes,1,opt,name=workflow,proto3" json:"workflow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowResponse) Reset() {
	*x = WorkflowResponse{}
	mi := &file_conduit_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowResponse) ProtoMessage() {}

func (x *WorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conduit_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowResponse.ProtoReflect.Descriptor instead.
func (*WorkflowResponse) Descriptor() ([]byte, []int) {
	return file_conduit_proto_rawDescGZIP(), []int{17}
}

func (x *WorkflowResponse) GetWorkflow() *WorkflowDef {
	if x != nil {
		return x.Workflow
	}
	return nil
}

type ListWorkflowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowsRequest) Reset() {
	*x = ListWorkflowsRequest{}
	mi := &file_conduit_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowsRequest) ProtoMessage() {}

func (x *ListWorkflowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conduit_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowsRequest.ProtoReflect.Descriptor instead.
func (*ListWorkflowsRequest) Descriptor() ([]byte, []int) {
	return file_conduit_proto_rawDescGZIP(), []int{18}
}

type ListWorkflowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workflows     []*WorkflowDef         `protobuf:"bytes,1,rep,name=workflows,proto3" json:"workflows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowsResponse) Reset() {
	*x = ListWorkflowsResponse{}
	mi := &file_conduit_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowsResponse) ProtoMessage() {}

func (x *ListWorkflowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conduit_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowsResponse.ProtoReflect.Descriptor instead.
func (*ListWorkflowsResponse) Descriptor() ([]byte, []int) {
	return file_conduit_proto_rawDescGZIP(), []int{19}
}

func (x *ListWorkflowsResponse) GetWorkflows() []*WorkflowDef {
	if x != nil {
		return x.Workflows
	}
	return nil
}

var File_conduit_proto protoreflect.FileDescriptor

const file_conduit_proto_rawDesc = "" +
	"\n" +
	"\rconduit.proto\x12\aconduit\"\xa2\x02\n" +
	"\x06Ticket\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bworkflow\x18\x02 \x01(\tR\bworkflow\x12)\n" +
	"\x10workflow_version\x18\x03 \x01(\tR\x0fworkflowVersion\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x1f\n" +
	"\vfields_json\x18\x05 \x01(\tR\n" +
	"fieldsJson\x12\x1a\n" +
	"\bassignee\x18\x06 \x01(\tR\bassignee\x12\x14\n" +
	"\x05queue\x18\a \x01(\tR\x05queue\x12\x1a\n" +
	"\bpriority\x18\b \x01(\tR\bpriority\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\"\x96\x01\n" +
	"\vWorkflowDef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\ainitial\x18\x04 \x01(\tR\ainitial\x12\x1d\n" +
	"\n" +
	"step_count\x18\x05 \x01(\x05R\tstepCount\"\xf5\x01\n" +
	"\vWorkflowRun\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tticket_id\x18\x02 \x01(\tR\bticketId\x12\x1a\n" +
	"\bworkflow\x18\x03 \x01(\tR\bworkflow\x12)\n" +
	"\x10workflow_version\x18\x04 \x01(\tR\x0fworkflowVersion\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12!\n" +
	"\fcurrent_step\x18\x06 \x01(\tR\vcurrentStep\x12\x1f\n" +
	"\voutput_json\x18\a \x01(\tR\n" +
	"outputJson\x12\x16\n" +
	"\x06failed\x18\b \x01(\bR\x06failed\"\x82\x01\n" +
	"\x13CreateTicketRequest\x12\x1a\n" +
	"\bworkflow\x18\x01 \x01(\tR\bworkflow\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1f\n" +
	"\vfields_json\x18\x04 \x01(\tR\n" +
	"fieldsJson\"?\n" +
	"\x14CreateTicketResponse\x12'\n" +
	"\x06ticket\x18\x01 \x01(\v2\x0f.conduit.TicketR\x06ticket\"e\n" +
	"\x0eApproveRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x12\n" +
	"\x04step\x18\x02 \x01(\tR\x04step\x12\x0e\n" +
	"\x02by\x18\x03 \x01(\tR\x02by\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\"b\n" +
	"\rRejectRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x12\n" +
	"\x04step\x18\x02 \x01(\tR\x04step\x12\x0e\n" +
	"\x02by\x18\x03 \x01(\tR\x02by\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\">\n" +
	"\rCancelRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\a\n" +
	"\x05Empty\"\"\n" +
	"\x10GetTicketRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x14\n" +
	"\x12ListTicketsRequest\"@\n" +
	"\x13ListTicketsResponse\x12)\n" +
	"\atickets\x18\x01 \x03(\v2\x0f.conduit.TicketR\atickets\"\x1f\n" +
	"\rGetRunRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"8\n" +
	"\x0eGetRunResponse\x12&\n" +
	"\x03run\x18\x01 \x01(\v2\x14.conduit.WorkflowRunR\x03run\"\x11\n" +
	"\x0fListRunsRequest\"<\n" +
	"\x10ListRunsResponse\x12(\n" +
	"\x04runs\x18\x01 \x03(\v2\x14.conduit.WorkflowRunR\x04runs\"B\n" +
	"\x12GetWorkflowRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"D\n" +
	"\x10WorkflowResponse\x120\n" +
	"\bworkflow\x18\x01 \x01(\v2\x14.conduit.WorkflowDefR\bworkflow\"\x16\n" +
	"\x14ListWorkflowsRequest\"K\n" +
	"\x15ListWorkflowsResponse\x122\n" +
	"\tworkflows\x18\x01 \x03(\v2\x14.conduit.WorkflowDefR\tworkflows2\x84\x05\n" +
	"\aConduit\x12K\n" +
	"\fCreateTicket\x12\x1c.conduit.CreateTicketRequest\x1a\x1d.conduit.CreateTicketResponse\x122\n" +
	"\aApprove\x12\x17.conduit.ApproveRequest\x1a\x0e.conduit.Empty\x120\n" +
	"\x06Reject\x12\x16.conduit.RejectRequest\x1a\x0e.conduit.Empty\x120\n" +
	"\x06Cancel\x12\x16.conduit.CancelRequest\x1a\x0e.conduit.Empty\x127\n" +
	"\tGetTicket\x12\x19.conduit.GetTicketRequest\x1a\x0f.conduit.Ticket\x12H\n" +
	"\vListTickets\x12\x1b.conduit.ListTicketsRequest\x1a\x1c.conduit.ListTicketsResponse\x129\n" +
	"\x06GetRun\x12\x16.conduit.GetRunRequest\x1a\x17.conduit.GetRunResponse\x12?\n" +
	"\bListRuns\x12\x18.conduit.ListRunsRequest\x1a\x19.conduit.ListRunsResponse\x12E\n" +
	"\vGetWorkflow\x12\x1b.conduit.GetWorkflowRequest\x1a\x19.conduit.WorkflowResponse\x12N\n" +
	"\rListWorkflows\x12\x1d.conduit.ListWorkflowsRequest\x1a\x1e.conduit.ListWorkflowsResponseB\x1cZ\x1atptconduit/api/proto;protob\x06proto3"

var (
	file_conduit_proto_rawDescOnce sync.Once
	file_conduit_proto_rawDescData []byte
)

func file_conduit_proto_rawDescGZIP() []byte {
	file_conduit_proto_rawDescOnce.Do(func() {
		file_conduit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conduit_proto_rawDesc), len(file_conduit_proto_rawDesc)))
	})
	return file_conduit_proto_rawDescData
}

var file_conduit_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_conduit_proto_goTypes = []any{
	(*Ticket)(nil),                // 0: conduit.Ticket
	(*WorkflowDef)(nil),           // 1: conduit.WorkflowDef
	(*WorkflowRun)(nil),           // 2: conduit.WorkflowRun
	(*CreateTicketRequest)(nil),   // 3: conduit.CreateTicketRequest
	(*CreateTicketResponse)(nil),  // 4: conduit.CreateTicketResponse
	(*ApproveRequest)(nil),        // 5: conduit.ApproveRequest
	(*RejectRequest)(nil),         // 6: conduit.RejectRequest
	(*CancelRequest)(nil),         // 7: conduit.CancelRequest
	(*Empty)(nil),                 // 8: conduit.Empty
	(*GetTicketRequest)(nil),      // 9: conduit.GetTicketRequest
	(*ListTicketsRequest)(nil),    // 10: conduit.ListTicketsRequest
	(*ListTicketsResponse)(nil),   // 11: conduit.ListTicketsResponse
	(*GetRunRequest)(nil),         // 12: conduit.GetRunRequest
	(*GetRunResponse)(nil),        // 13: conduit.GetRunResponse
	(*ListRunsRequest)(nil),       // 14: conduit.ListRunsRequest
	(*ListRunsResponse)(nil),      // 15: conduit.ListRunsResponse
	(*GetWorkflowRequest)(nil),    // 16: conduit.GetWorkflowRequest
	(*WorkflowResponse)(nil),      // 17: conduit.WorkflowResponse
	(*ListWorkflowsRequest)(nil),  // 18: conduit.ListWorkflowsRequest
	(*ListWorkflowsResponse)(nil), // 19: conduit.ListWorkflowsResponse
}
var file_conduit_proto_depIdxs = []int32{
	0,  // 0: conduit.CreateTicketResponse.ticket:type_name -> conduit.Ticket
	0,  // 1: conduit.ListTicketsResponse.tickets:type_name -> conduit.Ticket
	2,  // 2: conduit.GetRunResponse.run:type_name -> conduit.WorkflowRun
	2,  // 3: conduit.ListRunsResponse.runs:type_name -> conduit.WorkflowRun
	1,  // 4: conduit.WorkflowResponse.workflow:type_name -> conduit.WorkflowDef
	1,  // 5: conduit.ListWorkflowsResponse.workflows:type_name -> conduit.WorkflowDef
	3,  // 6: conduit.Conduit.CreateTicket:input_type -> conduit.CreateTicketRequest
	5,  // 7: conduit.Conduit.Approve:input_type -> conduit.ApproveRequest
	6,  // 8: conduit.Conduit.Reject:input_type -> conduit.RejectRequest
	7,  // 9: conduit.Conduit.Cancel:input_type -> conduit.CancelRequest
	9,  // 10: conduit.Conduit.GetTicket:input_type -> conduit.GetTicketRequest
	10, // 11: conduit.Conduit.ListTickets:input_type -> conduit.ListTicketsRequest
	12, // 12: conduit.Conduit.GetRun:input_type -> conduit.GetRunRequest
	14, // 13: conduit.Conduit.ListRuns:input_type -> conduit.ListRunsRequest
	16, // 14: conduit.Conduit.GetWorkflow:input_type -> conduit.GetWorkflowRequest
	18, // 15: conduit.Conduit.ListWorkflows:input_type -> conduit.ListWorkflowsRequest
	4,  // 16: conduit.Conduit.CreateTicket:output_type -> conduit.CreateTicketResponse
	8,  // 17: conduit.Conduit.Approve:output_type -> conduit.Empty
	8,  // 18: conduit.Conduit.Reject:output_type -> conduit.Empty
	8,  // 19: conduit.Conduit.Cancel:output_type -> conduit.Empty
	0,  // 20: conduit.Conduit.GetTicket:output_type -> conduit.Ticket
	11, // 21: conduit.Conduit.ListTickets:output_type -> conduit.ListTicketsResponse
	13, // 22: conduit.Conduit.GetRun:output_type -> conduit.GetRunResponse
	15, // 23: conduit.Conduit.ListRuns:output_type -> conduit.ListRunsResponse
	17, // 24: conduit.Conduit.GetWorkflow:output_type -> conduit.WorkflowResponse
	19, // 25: conduit.Conduit.ListWorkflows:output_type -> conduit.ListWorkflowsResponse
	16, // [16:26] is the sub-list for method output_type
	6,  // [6:16] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_conduit_proto_init() }
func file_conduit_proto_init() {
	if File_conduit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conduit_proto_rawDesc), len(file_conduit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_conduit_proto_goTypes,
		DependencyIndexes: file_conduit_proto_depIdxs,
		MessageInfos:      file_conduit_proto_msgTypes,
	}.Build()
	File_conduit_proto = out.File
	file_conduit_proto_goTypes = nil
	file_conduit_proto_depIdxs = nil
}
